"""Tests for the Markdown reporter."""

from datetime import datetime
from pathlib import Path
from unittest.mock import patch

import pytest

from license_tracker.models import LicenseLink, PackageMetadata
from license_tracker.reporters.markdown import MarkdownReporter


@pytest.fixture
def sample_packages():
    """Create sample package metadata for testing."""
    return [
        PackageMetadata(
            name="requests",
            version="2.31.0",
            description="HTTP library for Python",
            homepage="https://requests.readthedocs.io",
            repository_url="https://github.com/psf/requests",
            author="Kenneth Reitz",
            licenses=[
                LicenseLink(
                    spdx_id="Apache-2.0",
                    name="Apache-2.0",
                    url="https://github.com/psf/requests/blob/main/LICENSE",
                    is_verified_file=True,
                )
            ],
        ),
        PackageMetadata(
            name="click",
            version="8.1.7",
            description="Composable command line interface toolkit",
            homepage="https://palletsprojects.com/p/click/",
            repository_url="https://github.com/pallets/click",
            licenses=[
                LicenseLink(
                    spdx_id="BSD-3-Clause",
                    name="BSD-3-Clause",
                    url="https://github.com/pallets/click/blob/main/LICENSE.rst",
                    is_verified_file=True,
                )
            ],
        ),
    ]


@pytest.fixture
def root_project():
    """Create sample root project metadata."""
    return PackageMetadata(
        name="my-project",
        version="1.0.0",
        homepage="https://example.com",
        repository_url="https://github.com/me/my-project",
        licenses=[
            LicenseLink(
                spdx_id="MIT",
                name="MIT",
                url="https://github.com/me/my-project/blob/main/LICENSE",
                is_verified_file=True,
            )
        ],
        is_root_project=True,
    )


@pytest.fixture
def reporter():
    """Create a MarkdownReporter instance."""
    return MarkdownReporter()


def test_format_name(reporter):
    """Test that format_name returns 'markdown'."""
    assert reporter.format_name == "markdown"


def test_default_extension(reporter):
    """Test that default_extension returns '.md'."""
    assert reporter.default_extension == ".md"


def test_render_packages_to_markdown_table(reporter, sample_packages):
    """Test rendering packages to markdown table."""
    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        output = reporter.render(sample_packages)

        # Check header
        assert "# Open Source License Attribution" in output
        assert "## Dependencies" in output

        # Check table headers
        assert "| Library | Version | License | Source |" in output
        assert "|---------|---------|---------|--------|" in output

        # Check first package with hyperlinks
        assert "[requests](https://requests.readthedocs.io)" in output
        assert "2.31.0" in output
        assert "[Apache-2.0](https://github.com/psf/requests/blob/main/LICENSE)" in output
        assert "[Repository](https://github.com/psf/requests)" in output

        # Check second package
        assert "[click](https://palletsprojects.com/p/click/)" in output
        assert "8.1.7" in output
        assert "[BSD-3-Clause](https://github.com/pallets/click/blob/main/LICENSE.rst)" in output

        # Check footer
        assert "*Generated by license-tracker on 2025-11-26*" in output


def test_render_with_root_project(reporter, sample_packages, root_project):
    """Test rendering with root project section."""
    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        output = reporter.render(sample_packages, root_project=root_project)

        # Check root project section
        assert "## This Project" in output
        assert "[my-project](https://example.com)" in output
        assert "1.0.0" in output
        assert "[MIT](https://github.com/me/my-project/blob/main/LICENSE)" in output
        assert "[Repository](https://github.com/me/my-project)" in output

        # Check dependencies section still exists
        assert "## Dependencies" in output
        assert "[requests](https://requests.readthedocs.io)" in output


def test_render_package_without_homepage(reporter):
    """Test rendering package without homepage URL."""
    packages = [
        PackageMetadata(
            name="no-homepage",
            version="1.0.0",
            repository_url="https://github.com/test/no-homepage",
            licenses=[
                LicenseLink(
                    spdx_id="MIT",
                    name="MIT",
                    url="https://opensource.org/licenses/MIT",
                )
            ],
        )
    ]

    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        output = reporter.render(packages)

        # Should show plain text name without link
        assert "| no-homepage |" in output
        # Should not have homepage link
        assert "[no-homepage](" not in output


def test_render_package_without_repository(reporter):
    """Test rendering package without repository URL."""
    packages = [
        PackageMetadata(
            name="no-repo",
            version="1.0.0",
            homepage="https://example.com",
            licenses=[
                LicenseLink(
                    spdx_id="MIT",
                    name="MIT",
                    url="https://opensource.org/licenses/MIT",
                )
            ],
        )
    ]

    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        output = reporter.render(packages)

        # Should show N/A for source
        assert "| N/A |" in output


def test_render_package_without_license_url(reporter):
    """Test rendering package with license but no URL."""
    packages = [
        PackageMetadata(
            name="no-license-url",
            version="1.0.0",
            homepage="https://example.com",
            licenses=[
                LicenseLink(
                    spdx_id="MIT",
                    name="MIT License",
                    url="",
                )
            ],
        )
    ]

    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        output = reporter.render(packages)

        # Should show plain text license name without link
        assert "| MIT License |" in output
        # Should not have link
        assert "[MIT License](" not in output


def test_render_package_without_licenses(reporter):
    """Test rendering package with no license information."""
    packages = [
        PackageMetadata(
            name="no-license",
            version="1.0.0",
            homepage="https://example.com",
        )
    ]

    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        output = reporter.render(packages)

        # Should show Unknown for license
        assert "| Unknown |" in output


def test_render_package_with_multiple_licenses(reporter):
    """Test rendering package with multiple licenses (dual-licensed)."""
    packages = [
        PackageMetadata(
            name="dual-licensed",
            version="1.0.0",
            homepage="https://example.com",
            licenses=[
                LicenseLink(
                    spdx_id="MIT",
                    name="MIT",
                    url="https://opensource.org/licenses/MIT",
                ),
                LicenseLink(
                    spdx_id="Apache-2.0",
                    name="Apache-2.0",
                    url="https://opensource.org/licenses/Apache-2.0",
                ),
            ],
        )
    ]

    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        output = reporter.render(packages)

        # Should show both licenses with comma separator
        assert "[MIT](https://opensource.org/licenses/MIT)" in output
        assert "[Apache-2.0](https://opensource.org/licenses/Apache-2.0)" in output
        # Check they're on the same line (in same cell)
        lines = output.split("\n")
        dual_line = [line for line in lines if "dual-licensed" in line][0]
        assert "MIT" in dual_line and "Apache-2.0" in dual_line


def test_custom_template_loading(tmp_path):
    """Test loading a custom template from file."""
    # Create a custom template
    custom_template = tmp_path / "custom.md.j2"
    custom_template.write_text(
        "# Custom Template\n"
        "Packages: {{ packages|length }}\n"
        "{% for pkg in packages -%}\n"
        "- {{ pkg.name }}\n"
        "{% endfor %}"
    )

    reporter = MarkdownReporter(template_path=custom_template)

    packages = [
        PackageMetadata(name="test1", version="1.0.0"),
        PackageMetadata(name="test2", version="2.0.0"),
    ]

    output = reporter.render(packages)

    assert "# Custom Template" in output
    assert "Packages: 2" in output
    assert "- test1" in output
    assert "- test2" in output


def test_write_to_file(reporter, sample_packages, tmp_path):
    """Test writing rendered output to a file."""
    output_file = tmp_path / "licenses.md"

    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        reporter.write(sample_packages, output_file)

        assert output_file.exists()
        content = output_file.read_text(encoding="utf-8")
        assert "# Open Source License Attribution" in content
        assert "[requests](https://requests.readthedocs.io)" in content


def test_empty_packages_list(reporter):
    """Test rendering with empty packages list."""
    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        output = reporter.render([])

        # Should still have structure
        assert "# Open Source License Attribution" in output
        assert "## Dependencies" in output
        assert "| Library | Version | License | Source |" in output


def test_root_project_without_optional_fields(reporter, sample_packages):
    """Test root project with minimal information."""
    minimal_root = PackageMetadata(
        name="minimal",
        version="0.1.0",
        is_root_project=True,
    )

    with patch("license_tracker.reporters.markdown.datetime") as mock_datetime:
        mock_datetime.now.return_value = datetime(2025, 11, 26, 12, 0, 0)

        output = reporter.render(sample_packages, root_project=minimal_root)

        # Should show plain name without links
        assert "| minimal |" in output
        assert "0.1.0" in output
        assert "| Unknown |" in output  # No license
        assert "| N/A |" in output  # No repository
